pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir .public
    - cp -r docs/* .public
    - mv .public public
    - ls public
  artifacts:
    paths:
      - public
  only:
    - master
