pages:
  stage: deploy
  script:
    - mkdir tmppublic
    - mv public tmppublic
    - ls tmpublic
    - mkdir .public
    - cp -r docs/ .public
    - mv .public public
    - ls public
  artifacts:
    paths:
      - public
  only:
    - master
