pages:
  stage: deploy
  script:
    - mkdir tmp-public
    - mv public tmp-public
    - ls tmp-public
    - mkdir .public
    - cp -r docs/ .public
    - mv .public public
    - ls public
  artifacts:
    paths:
      - public
  only:
    - master
